### PR TITLE
Add merge function

### PR DESCRIPTION
**Pull request by martindurant**
Thoughts?

### CODE REVIEW

**Comment by douglasdavis** [comment]
This does seem a bit more elegant (not using `ak.zip`) compared to what I had going in #9. I do like the idea of having an argument for defining which columns to merge, perhaps `=None` defaulting to all columns into a single Series

**Comment by martindurant** [comment]
Dataframes are pretty easy to select columns from. My code will fail in the presence of unnamed columns or duplicate labels.

**Comment by martindurant** [comment]
Didn't notice your pr

**Comment by martindurant** [comment]
OK, so comparing the two PRS...
I think that allowing to set the name is a good idea, and support it; although it's easy enough to set the attribute afterwards, this allows for inline expressions. Actually, I don't really know what the name is used for when not a column of a dataframe, but never mind.
For the columns argument, I am against, because
```
merge(dataframe, columns), merge(dataframe[columns])
```
are identical, and I think the one with select is clearer and more like normal pandas usage.

As to ak.zip versus calling ak.Array with a dict, I suspect that these are also identical underneath. It would be good to get an opinion from @jpivarski on what can and can't be passed to both these and if there are any drawback to be aware of (aside from requiring unique string field names; and we aren't checking for object/str types yet).

**Comment by jpivarski** [comment]
They're not identical:

```python
>>> import awkward._v2 as ak
>>> x = ak.Array([[1, 2, 3], [], [4, 5]])
>>> y = ak.Array([[6, 7, 8], [], [9, 10]])

>>> ak.Array({"x": x, "y": y}).show(type=True)   # makes records of lists
type: 3 * {
    x: var * int64,
    y: var * int64
}
[{x: [1, 2, 3], y: [6, 7, 8]},
 {x: [], y: []},
 {x: [4, 5], y: [9, 10]}]

>>> ak.zip({"x": x, "y": y}).show(type=True)   # makes lists of records
type: 3 * var * {
    x: int64,
    y: int64
}
[[{x: 1, y: 6}, {x: 2, y: 7}, {x: 3, y: 8}],
 [],
 [{x: 4, y: 9}, {x: 5, y: 10}]]
```

but [ak.zip](https://awkward-array.readthedocs.io/en/latest/_auto/ak.zip.html) with `depth_limit=1` would be identical to the dict-based [ak.Array](https://awkward-array.readthedocs.io/en/latest/_auto/ak.Array.html) constructor.

```python
>>> ak.zip({"x": x, "y": y}, depth_limit=1).show(type=True)
type: 3 * {
    x: var * int64,
    y: var * int64
}
[{x: [1, 2, 3], y: [6, 7, 8]},
 {x: [], y: []},
 {x: [4, 5], y: [9, 10]}]
```

They'd also be the same if the inputs only have a depth of 1.

The purpose of the dict-based constructor is so that an `ak.Array` can be constructed like a `pd.DataFrame`, and this just puts arrays together into columns—therefore, it does not change the internal structure of what it's given. The `ak.zip` function is supposed to "zip", to change the structure the way that Python's `zip([1, 2, 3], ["a", "b", "c"])` makes new `[(1, "a"), (2, "b"), (3, "c")]` tuples, except that `ak.zip` can descend to any depth and can add field names, making records, rather than tuples.

I guess the question here is what do you want `merge` to do? Should it deeply zip its inputs or not?

**Comment by martindurant** [comment]
> I guess the question here is what do you want merge to do? Should it deeply zip its inputs or not?

I think the answer is "no". Having said that, the use case is only none or one awkward input and the rest 1d normal pandas columns (i.e., numpy arrays), so indeed depth 1 at least most of the time. 

(We will need something explicit to deal with object arrays containing lists/dicts and for string/string[pyarrow])

**Comment by martindurant** [comment]
@douglasdavis , this is far as I intend on taking things in this PR

**Pull request merged**
