### PR TITLE
Some string stuff

### PR DESCRIPTION
**Pull request by martindurant**
```
In [1]: import pandas as pd

In [2]: import awkward_pandas

In [3]: s = pd.Series(["hello", "world"]*1000000, dtype='awkward')

In [4]: %timeit s.ak.upper()
20.9 ms ± 1.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [5]: slist = ["hello", "world"]*1000000

In [6]: %timeit [_.upper() for _ in slist]
227 ms ± 4.11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

### CODE REVIEW

**Comment by martindurant** [comment]
Seems to work with strings, but not bytestrings (`no kernel matching input types (array[binary])`)

**Comment by martindurant** [comment]
cc @jpivarski

**Comment by jpivarski** [comment]
Nice! I'd like to have these functions in core Awkward, too, though. I know that it implies a soft dependency on pyarrow. If you develop it here, would it be easy to factorize the part that does the calculation (in `ak.str.*` functions) from the part that maps it to Series methods (`my_series.ak.*` or `my_series.str.*`)?

That factor of 10 speedup should be a good selling point!

**Comment by martindurant** [comment]
@douglasdavis , your opinion on how many string operations should be tested here before we can - cautiously - merge this?

**Comment by douglasdavis** [comment]
Since this is pulling in string operations from another library my opinion would be "not many", since really what needs to be tested is the accessor doing what we expect it to do.

**Comment by martindurant** [comment]
There are many rough edges here, such as what to do with list[str] or ?str (these don't currently get any string functions, we would have to "unroll" them before passing to arrow), but I thin this is good for demo.

**Pull request merged**
