### PR TITLE
Extract ak.Array type for repr

### PR DESCRIPTION
**Pull request by mroeschke**
Might be helpful in the `DataFrame/Series` repr to see what the type of the array is. LMK if this would be desired.

### CODE REVIEW

**Comment by martindurant** [comment]
I feel like this string might be very long in some cases. Is there a reasonable limit to how many characters we should return?

**Comment by mroeschke** [comment]
Ah fair point. Not off the top of my head, but I believe the pandas repr _should_ truncate according to the default formatting options: https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

Maybe instead a new method could be provided e.g. `ak.array_type` to return the type separately?

**Comment by martindurant** [comment]
@mroeschke , at some point, we discussed some workflows that you had come across that would be hard/slow to do in pure pandas but might suit this project. Any chance you can create an issue with as many details as you can gather?

Also, you'd be very welcome to discuss your thoughts on moving ahead with the awkward team, either at our Thursday morning sync-up or any other time that's convenient for you and @jpivarski .

**Comment by jpivarski** [comment]
Good to meet you, @mroeschke!

Types can be very verbose. Given this dataset,

```python
>>> import awkward._v2 as ak
>>> array = ak.from_parquet("https://pivarski-princeton.s3.amazonaws.com/chicago-taxi.parquet", row_groups=[0])
```

The type `__repr__` is long and ugly,

```python
>>> array.type
ArrayType(ListType(RecordType([RecordType([OptionType(NumpyType('float32')), OptionType(NumpyType('float32')), RecordType([OptionType(NumpyType('float64')), OptionType(NumpyType('float64')), OptionType(NumpyType('datetime64[ms]'))], ['lon', 'lat', 'time']), RecordType([OptionType(NumpyType('float64')), OptionType(NumpyType('float64')), OptionType(NumpyType('datetime64[ms]'))], ['lon', 'lat', 'time']), ListType(RecordType([NumpyType('float32'), NumpyType('float32')], ['londiff', 'latdiff']))], ['sec', 'km', 'begin', 'end', 'path']), RecordType([OptionType(NumpyType('float32')), OptionType(NumpyType('float32')), OptionType(NumpyType('float32')), ListType(NumpyType('uint8', parameters={'__array__': 'char'}, typestr='char'), typestr='string')], ['fare', 'tips', 'total', 'type']), ListType(NumpyType('uint8', parameters={'__array__': 'char'}, typestr='char'), typestr='string')], ['trip', 'payment', 'company'])), 353)
```

but the type `__str__` is a little better, in [Datashape](https://datashape.readthedocs.io/) format.

```python
>>> print(array.type)
353 * var * {trip: {sec: ?float32, km: ?float32, begin: {lon: ?float64, lat: ?float64, time: ?datetime64[ms]}, end: {lon: ?float64, lat: ?float64, time: ?datetime64[ms]}, path: var * {londiff: float32, latdiff: float32}}, payment: {fare: ?float32, tips: ?float32, total: ?float32, type: string}, company: string}
```

The output of `show` is ideal for a complicated case like this, in that it's multi-line:

```python
>>> import io
>>> tmp = io.StringIO()
>>> array.type.show(stream=tmp)
>>> print(tmp.getvalue())
353 * var * {
    trip: {
        sec: ?float32,
        km: ?float32,
        begin: {
            lon: ?float64,
            lat: ?float64,
            time: ?datetime64[ms]
        },
        end: {
            lon: ?float64,
            lat: ?float64,
            time: ?datetime64[ms]
        },
        path: var * {
            londiff: float32,
            latdiff: float32
        }
    },
    payment: {
        fare: ?float32,
        tips: ?float32,
        total: ?float32,
        type: string
    },
    company: string
}
```

but that's not going to be useful in the `__repr__` of a dtype, if that's what you're looking for. In that case, the best you can do is to truncate the `__str__`, as we do for the `ak.Array.__repr__`.

```python
>>> array
<Array [[{trip: {...}, ...}, ..., {...}], ...] type='353 * var * {trip: {se...'>
```

But then, arrays that are going into Pandas would be exploded, since Pandas can already handle top-level columns. For this `array`, that would mean,

```python
>>> exploded = dict(zip(ak.fields(array), ak.unzip(array)))
>>> exploded["trip"].type.show()
353 * var * {
    sec: ?float32,
    km: ?float32,
    begin: {
        lon: ?float64,
        lat: ?float64,
        time: ?datetime64[ms]
    },
    end: {
        lon: ?float64,
        lat: ?float64,
        time: ?datetime64[ms]
    },
    path: var * {
        londiff: float32,
        latdiff: float32
    }
}
>>> exploded["payment"].type.show()
353 * var * {
    fare: ?float32,
    tips: ?float32,
    total: ?float32,
    type: string
}
>>> exploded["company"].type.show()
353 * var * string
```

Maybe two levels of exploding for this `array`:

```python
>>> exploded2 = dict(zip(ak.fields(exploded["trip"]), ak.unzip(exploded["trip"])))
>>> exploded2["sec"].type.show()
353 * var * ?float32
>>> exploded2["km"].type.show()
353 * var * ?float32
>>> exploded2["begin"].type.show()
353 * var * {
    lon: ?float64,
    lat: ?float64,
    time: ?datetime64[ms]
}
>>> exploded2["end"].type.show()
353 * var * {
    lon: ?float64,
    lat: ?float64,
    time: ?datetime64[ms]
}
>>> exploded2["path"].type.show()
353 * var * var * {
    londiff: float32,
    latdiff: float32
}
```

Pandas users probably wouldn't be interested in the length of each array, since they'd all be identical in a DataFrame (the 353 above). Also, the DataFrame displays that value elsewhere, not in the dtype. In an Awkward Type, it's encoded as an outer layer (Python class is `ArrayType`), which can be stripped off:

```python
>>> print(exploded2["sec"].type.content)
var * ?float32
>>> print(exploded2["km"].type.content)
var * ?float32
>>> print(exploded2["begin"].type.content)
var * {lon: ?float64, lat: ?float64, time: ?datetime64[ms]}
>>> print(exploded2["end"].type.content)
var * {lon: ?float64, lat: ?float64, time: ?datetime64[ms]}
>>> print(exploded2["path"].type.content)
var * var * {londiff: float32, latdiff: float32}
```

These strings are perhaps the most useful, even if you have to truncate them to a maximum number of characters.

As Arrow, rather than Awkward, I don't see an option for a user (data analyst)-friendly string:

```python
>>> ak.to_arrow(exploded2["path"], extensionarray=False).type
ListType(list<item: large_list<item: struct<londiff: float not null, latdiff: float not null> not null> not null>)

>>> print(ak.to_arrow(exploded2["path"], extensionarray=False).type)
list<item: large_list<item: struct<londiff: float not null, latdiff: float not null> not null> not null>
```

At least, not as a member function. Maybe there's something that I don't know about.

**Comment by mroeschke** [comment]
Yeah given the verbosity of potential types in awkward, this enhancement is probably not worth moving forward.

@martindurant I'll open up an issue with operations that are not easy to do in pandas but might be suitable for awkward. In terms of moving forward, I don't have too much time to help develop the actual awkward ExtensionArray or ExtensionDtype, but I am eager to chime in if there are pandas semantics questions or and bugs uncovered when developing the array or dtype

**Pull request closed without merging**
